[package]
name = "simplediscord"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
iced = { git = "https://github.com/iced-rs/iced", branch = "master", features= ["svg"] }
poise = "0.6.1"
tokio = { version = "1.47.1", features = ["full"] }
